prometheus-exporters-formula/metadata/form.yml
prometheus-exporters-formula/metadata/pillar.example
prometheus-exporters-formula/prometheus-exporters/config.sls
prometheus-exporters-formula/prometheus-exporters/files/postgres-exporter-config
prometheus-exporters-formula/prometheus-exporters/init.sls
prometheus-exporters-formula/prometheus-exporters/map.jinja

This patch adds support for installing, enabling and configuring the `postgres-exporter` to the `prometheus-exporters-formula`.

Add support for postgres-exporter

---

prometheus-exporters-formula/prometheus-exporters/map.jinja

With our latest packages the service is named `prometheus-postgres_exporter`, the salt state needs to follow this change.

Rename the postgres exporter service

---

cpu-mitigations-formula/states/init.sls
cpu-mitigations-formula/states/map.jinja

There was an issue with the sumaform image sp3 , So the option should end with the _DEFAULT... 
(This option is a grub option and not a specific to SUSE).  
I also refactored some of the state so it's cleaner.

Fix issue with default grub line entry and refactor refactor state

---

prometheus-exporters-formula/prometheus-exporters/files/node-exporter-config.Debian

The configuration file that is shipped with version 0.17.0 of `prometheus-node-exporter` has changed, so this patch is updating it. This change should not be critical as only the (commented out) listing of options is changed.

Update the Debian config file to version 0.17.0

---

pxe-formula/pxe-formula.changes
pxe-formula/pxe/map.jinja

- Leap15 shares SLE15 paths so make them default and only check for SLE12
- This enables pxe formula for Uyuni

Fix missing EFI path on non-SLE systems

---

pxe-formula/pxe-formula.changes
pxe-formula/pxe/files/pxecfg.grub2.template

Relative paths do not work with USB. For PXE boot both work OK.

Use absolute paths in grub2 config

---

pxe-formula/form.yml
pxe-formula/pxe-formula.changes
pxe-formula/pxe/files/pxecfg.template

- new options for terminal naming now can be specified in pillars
and this commit parse them to correctly set kernel command line
- branch_id field removed from pxe form and moved to branch-network

Add support for new features in terminal naming

---

prometheus-formula/metadata/form.yml
prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus-formula.spec
prometheus-formula/prometheus/files/prometheus.yml

The change enables configuration of federated Prometheus setup. It assumes matching metric names according to to the specified list of matching patterns. The default is set to:
`{__name__=~"node:.*"}`
which matches all recording rules with the prefix `node:`. The corresponding recording rules have to be defined on the cluster's (e.g. CaaSP) Prometheus server.

Add federation setup to Prometheus formula

---

prometheus-formula/metadata/form.yml
prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/files/general-rules.yml
prometheus-formula/prometheus/files/prometheus-rules.yml
prometheus-formula/prometheus/files/prometheus.yml
prometheus-formula/prometheus/init.sls

The change configures scraping Prometheus metrics from local and remote Prometheus instances and defines a set of default alerting rules based on these measurements.

Add meta monitoring for Prometheus

---

pxe-formula/pxe-formula.changes
pxe-formula/pxe/files/pxecfg.grub2.template

This is used only in usb boot image.

Add non-EFI grub menu variant to pxe formula

---

grafana-formula/grafana-formula.changes
grafana-formula/grafana-formula.spec
grafana-formula/grafana/init.sls

When main configuration file or any of datasources or dashboards are
changed the service has to be restarted for changes to take effect. Modified formula watches for updates in these files to trigger restart.

Restart Grafana on configuration changes

---

virtualization-host-formula/metadata/form.yml

Using required in a conditionally visible field needs to have a condition that matches its visibility.

virtualization host: fix required conditions

---

openvpn-formula/metadata/form.yml
openvpn-formula/metadata/metadata.yml
openvpn-formula/openvpn-formula.changes
openvpn-formula/openvpn-formula.spec
openvpn-formula/openvpn/common.sls
openvpn-formula/openvpn/files/_gateway.conf
openvpn-formula/openvpn/files/_subnet.conf
openvpn-formula/openvpn/files/ipp.txt
openvpn-formula/openvpn/files/server.conf
openvpn-formula/openvpn/init.sls
openvpn-formula/openvpn/map.jinja
openvpn-formula/openvpn/server/init.sls
openvpn-formula/openvpn/server/service.sls

Users can use the Uyuni/SUMA form to configure an OpenVPN server. The formula installs the needed packages, enables the service and populates the `/etc/openvpn/server.conf` template with values from the from.
I've taken this [formula](https://github.com/salt-formulas/salt-formula-openvpn) (also Apache-2.0 licensed) and adapted it a little.
Related: https://github.com/SUSE/spacewalk/issues/11173

Add formula for openvpn (server)

---

openvpn-formula/openvpn-formula.changes

We should not rewrite the changelog after it was released. This reverts the changelog to what we released + recent changes on top.

Re-align tracked changelog with released version

---

virtualization-host-formula/metadata/form.yml
virtualization-host-formula/virtualization-host/init.sls
virtualization-host-formula/virtualization-host/map.jinja

Squash a few virtualization host fixes in a PR.
Fixes:
* SUSE/spacewalk#11953 (bridged default network)
* SUSE/spacewalk#11996 (kernel-default)
* Ensure we have python3 libvirt binding

virtualization host: misc fixes

---

uyuni-config-formula/uyuni-config-formula.spec

uyuni-config-formula: fix spec typo

---

uyuni-config-formula/README.md
uyuni-config-formula/metadata/form.yml
uyuni-config-formula/metadata/pillar.example
uyuni-config-formula/uyuni-config-formula.changes
uyuni-config-formula/uyuni-config/init.sls

Update salt uyuni configuration formula to allow manage activation keys
Part of: https://github.com/SUSE/spacewalk/issues/12495
Signed-off-by: Ricardo Mateus <rmateus@suse.com>

configration formula add support for activation keys

---

grafana-formula/grafana-formula.changes
grafana-formula/metadata/form.yml
prometheus-formula/metadata/form.yml
prometheus-formula/prometheus-formula.changes

The variable is dynamically set in UI to _Uyuni_ or _SUSE Manager_ to
avoid users' confusion.
Fixes SUSE/spacewalk#12469

Use variable for product name

---

pxe-formula/form.yml
pxe-formula/pillar.example
pxe-formula/pxe-formula.changes
pxe-formula/pxe/files/pxecfg.grub2.template
pxe-formula/pxe/files/pxecfg.template

Fixes https://github.com/SUSE/spacewalk/issues/12162
Depends on https://github.com/uyuni-project/retail/pull/64

Change default to initrd without .gz suffix

---

prometheus-exporters-formula/metadata/pillar.example
prometheus-exporters-formula/prometheus-exporters-formula.changes

Reverse proxy for Prometheus should get installed only when actively
activated by the user. It assures the backwards compatibility with
existing deployments.
(cherry picked from commit 64b891aeb2de0d0ea5c4e921c824df21df395fd3)

Disable Prometheus exporters' reverse proxy (#82)

---

prometheus-exporters-formula/metadata/pillar.example
prometheus-exporters-formula/prometheus-exporters-formula.changes

When default values are used for initialization of formula data, empty
dictionary values are serialized as null objects. This causes
NullPointerException in Xml Serializer of FormulaData object on the
server side.
Fixes: https://github.com/uyuni-project/uyuni/issues/2651

Remove empty dictionary values initialization

---

bind-formula/bind-formula.changes
bind-formula/bind/files/suse/named.conf

Once SUMA formula rendering is enhanced to cope with list of values mixed together with predefined values I'll revert this fix and use proper form.yml.

Temporarily disable dnssec-validation as hotfix for bsc#1177790

---

tftpd-formula/form.yml
tftpd-formula/tftpd-formula.changes

I was contacted that customer was surprised tftp formula now requires entering an IP address. There was not a change in behaviour and customer probably had a space in the formula field.
Here I'm adding a match check to check either completely empty value or correct IP address.

Add IP or empty string match for tftp formula

---

pxe-formula/pxe-formula.changes
pxe-formula/pxe/files/pxecfg.grub2.template

linuxefi grub command does not work on arm, this change is copied from Kiwi OEM image configuration.

Use linuxefi only on x86

---

prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/files/mgr-server.yml
prometheus-formula/prometheus/files/prometheus.yml
prometheus-formula/prometheus/init.sls

When the minion with Prometheus server is registered on the proxy and
not directly on the Uyuni server, Prometheus should be configured with
Uyuni server hostname and not Salt master which is set to proxy minion
in this setup.
Fixes SUSE/spacewalk#13543

[prometheus] Set server hostname from pillar data

---

prometheus-exporters-formula/prometheus-exporters-formula.changes
prometheus-exporters-formula/prometheus-exporters/files/exporter-proxy.yaml
prometheus-exporters-formula/prometheus-exporters/init.sls

In the new formula data schema exporters' configuration has been moved
to `exporters` field.
Also, full [exporter key name](https://github.com/uyuni-project/prometheus-uyuni-sd/commit/1eb8cf162a9ee166083a24704c51ea74c28406df#diff-7c95b54a215ed562472b3db7123a8cbf788db6f9f08d6b74adcfd6b8f0d28d74R261) is used for the module name now.

[prometheus-exporters] Fix exporter exporter configuration

---

prometheus-exporters-formula/prometheus-exporters-formula.changes
prometheus-exporters-formula/scripts/migrate_formula_data.py

Fix formula data migration script to handle the case when one of exporter configuration dictionaries is missing.
Steps to reproduce:
Run the migration script with the following formula data:
```
{
"node_exporter": {
"enabled": true,
"args": "--web.listen-address\u003d\":9100\""
},
"postgres_exporter": {
"enabled": false,
"data_source_name": "postgresql://user:passwd@localhost:5432/database?sslmode\u003ddisable",
"args": "--web.listen-address\u003d\":9187\""
}
}
```
Fixes: https://github.com/SUSE/spacewalk/issues/15350

[prometheus-exporters] Fix missing exporter in formula data migration

---

prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/files/prometheus.yml
prometheus-formula/prometheus/files/prometheus_old.yml
prometheus-formula/prometheus/init.sls
prometheus-formula/prometheus/map.jinja

Prometheus 2.31 includes upstream Uyuni SD with different configuration options and different set of returned labels.
This change checks the version of the installed Prometheus package and applies the appropriate configuration template to provide unchanged user experience.

Add support for Prometheus>=2.31

---

prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/files/prometheus.yml
prometheus-formula/prometheus/files/prometheus_old.yml

Update blackbox exporter configuration for Prometheus 2.32
(cherry picked from commit ee3bf947278496801b21f82bb1f3cf97821da3ff)
Fixes: https://github.com/SUSE/spacewalk/issues/16744

[Manager-4.1] Fix Blackbox exporter configuration for Prometheus >= 2.31

---

prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/init.sls
prometheus-formula/prometheus/map.jinja

Prometheus formula is currently supported only for SUSE systems.
The change hardens the formula to allow its application only to
supported systems. Additionally, the variables map can be extended by
the customer by setting the values in `prometheus:lookup` pillar.
(cherry picked from commit c71947edfc1e7e0cdfacab22053bcd11646eaff3)

Allow prometheus-formula only for SUSE systems (#174)

---

grafana-formula/grafana-formula.changes
grafana-formula/metadata/form.yml

The field `admin_password` is used to set up the initial value of the default admin password during the first run of Grafana. It cannot be used to change the password afterwards.
This change is an attempt to be more specific about the purpose of the field.
Fixes: SUSE/spacewalk#19108

[grafana] Fix default admin password field name

---

prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/files/prometheus.yml

Targets in clients job now use the correct scheme label.

[prometheus] Fix scheme relabeling configuration

---

grafana-formula/grafana-formula.changes
grafana-formula/grafana/files/mgr-apache.json
grafana-formula/grafana/files/mgr-client-systems.json
grafana-formula/grafana/files/mgr-postgresql.json
grafana-formula/grafana/files/mgr-server.json

Additionally,
* replace the use of `hostname` label in queries with more generic `instance`,
* migrate deprecated panels to their current replacements

[grafana] Migrate dashboards to new JSON schema

---

grafana-formula/grafana-formula.changes
grafana-formula/grafana/init.sls

The state uses pillar item `mgr_server_is_uyuni` now instead of grain item `is_uyuni` which contained wrong data.
Fixes SUSE/spacewalk#19584

Fix Uyuni/SUMA dashboard names

---

grafana-formula/grafana/init.sls

Client tools channel is not available in a Proxy/Retail using as base channel the Proxy/Retail Products.
So, we can't show the Grafana formula if we are in a SLES Operating System that has a Proxy pattern installed (as we can guess from that that we are in a SUMA/Uyuni Proxy/Retail).
**Note:** I did not open a bug report about it. Let me know if I should open one or we are fine without it @mcalmer

Grafana formula should not be supported in a Proxy/Retail

---

prometheus-formula/prometheus/files/prometheus-rules.yml

SUSE Manager shows the same behaviour as described in https://github.com/prometheus/prometheus/issues/7293, causing false alerts.
This change is a backport of https://github.com/prometheus/prometheus/pull/8054/

improve PrometheusNotIngestingSamples

---

prometheus-formula/metadata/form.yml
prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/files/prometheus.yml

Add a list of groups to the Prometheus formula for which service discovery targets are filtered. All matching targets are kept, remaining ones dropped.
Implements SUSE/spacewalk#23129
New form:
Resulting service discovery targets:

[prometheus] Add group filtering for SD

---

grafana-formula/grafana-formula.changes
grafana-formula/grafana/files/mgr-server.json.jinja

Replace legacy message queue panel metrics with new Salt queue metrics introduced in uyuni-project/uyuni#8050.

[grafana] Update message queue panel

---

prometheus-formula/metadata/form.yml
prometheus-formula/prometheus-formula.changes
prometheus-formula/prometheus/files/prometheus-service.conf
prometheus-formula/prometheus/files/prometheus.yml
prometheus-formula/prometheus/init.sls

The change adds support for configuring Prometheus remote write protocol configuration for pushing samples to a compatible external storage system.  
It also allows to run Prometheus with remote write receiver enabled for the instance accepting metrics from another Prometheus server.
Implements SUSE/spacewalk#23360
New UI:

[prometheus] Add remote write configuration

---

prometheus-exporters-formula/prometheus-exporters-formula.changes
prometheus-exporters-formula/prometheus-exporters/map.jinja

Fix the typo in the Debian service name for PostgreSQL exporter
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1226605

Fix PostgreSQL exporter service name on Debian

---

prometheus-exporters-formula/prometheus-exporters-formula.changes
prometheus-exporters-formula/prometheus-exporters/init.sls

As described in the title.
In the context of https://bugzilla.suse.com/show_bug.cgi?id=1226035

Fix `--web.config.file` flag name for web configuration file for TLS support

---

Makefile
pxe-formula/pxe-formula.changes
pxe-formula/pxe-formula.spec
pxe-formula/pxe/files/pxecfg.grub2.template
pxe-formula/pxe/files/pxecfg.template

PXE formula part for https://github.com/SUSE/spacewalk/issues/24801
Standardizing PXE formula releasing as the other formulas and bumping version number to 0.2.0
Change in changes files seems wrong, but the formula with that change was never released and build team complained before when we had duplicated entries.
Issue: https://github.com/SUSE/spacewalk/issues/24801

Add MAC based terminal naming option

---

pxe-formula/pxe-formula.changes
pxe-formula/pxe-formula.spec
pxe-formula/pxe/init.sls
pxe-formula/pxe/map.jinja
pxe-formula/pxe/uninstall.sls
tftpd-formula/tftpd-formula.changes
tftpd-formula/tftpd-formula.spec
tftpd-formula/tftpd/init.sls
tftpd-formula/tftpd/map.jinja
tftpd-formula/tftpd/uninstall.sls

- license is GPL-2.0
- spec-clean tftp and pxe formula spec files

Fix license versions for tftp and pxe formulas

---

liberate-formula/liberate-formula.changes
liberate-formula/liberate/init.sls
liberate-formula/metadata/form.yml

Change the default value to `false` in order to not have all packages reinstalled after conversion, i.e. a liberation would only change the channel subscriptions.

Do not reinstall all packages per default
