- LICENSE
> add apache 2.0 license file to root dir

- bind-formula/bind-formula.changes
- bind-formula/form.yml
Improvements to bind form:
* remove wrong default for bind options preventing correct upload
of bind options using XMLRPC (needed for https://github.com/SUSE/spacewalk/issues/9431)
* add explaining names to CNAME and A sections
> Improvements to bind form

- prometheus-formula/LICENSE
- prometheus-formula/metadata/form.yml
- prometheus-formula/metadata/metadata.yml
- prometheus-formula/metadata/pillar.example
- prometheus-formula/prometheus-formula.changes
- prometheus-formula/prometheus-formula.spec
- prometheus-formula/prometheus/files/mgr-server.yml
- prometheus-formula/prometheus/files/prometheus.yml
- prometheus-formula/prometheus/init.sls
- prometheus-formula/prometheus/map.jinja
Formula for configuring Prometheus instance.
**Note:** depends on enhancements from https://github.com/uyuni-project/uyuni/pull/1527.
> Prometheus formula

- Makefile
- grafana-formula/LICENSE
- grafana-formula/grafana-formula.changes
- grafana-formula/grafana-formula.spec
- grafana-formula/grafana/files/dashboard-provider.yml
- grafana-formula/grafana/files/datasources.yml
- grafana-formula/grafana/files/grafana.ini
- grafana-formula/grafana/files/mgr-apache.json
- grafana-formula/grafana/files/mgr-client-systems.json
- grafana-formula/grafana/files/mgr-postgresql.json
- grafana-formula/grafana/files/mgr-server.json
- grafana-formula/grafana/init.sls
- grafana-formula/metadata/form.yml
- grafana-formula/metadata/metadata.yml
Formula for configuring Grafana.
**Note:** depends on enhancements from https://github.com/uyuni-project/uyuni/pull/1527.
> Formula for Grafana

- prometheus-formula/metadata/form.yml
- prometheus-formula/prometheus-formula.changes
- Fix the `$disabled` expressions 
- Use newer `$visible` instead of deprecated `$visibleIf`.
> Fix $disabled expressions in prometheus formula

- prometheus-formula/prometheus-formula.changes
`prometheus-formula` changelog update.
> prometheus-formula changelog update

- pxe-formula/pxe-formula.changes
I was too quick and used wrong released number to update changelog.
> Fix wrong version number in changes

- virtualization-host-formula/virtualization-host/_states/bootloader.py
Addressing @aplanas comments in PR #35
> Code beautification in bootloader.py

- pxe-formula/pxe-formula.changes
- pxe-formula/pxe/files/pxecfg.grub2.base
- pxe-formula/pxe/files/pxecfg.grub2.template
This allows booting from http subdirectory.
> Use grub2 variable "prefix" instead of hardcoded /boot

- system-lock-formula/metadata/form.yml
- system-lock-formula/metadata/metadata.yml
Clarify terms used in system lock formula and adapt them to Uyuni/SUSE Manager.
> Refactor: clarify/adapt terms

- grafana-formula/grafana-formula.changes
As per https://en.opensuse.org/openSUSE:Creating_a_changes_file_(RPM)#Version_updates
I already fixed it at OBS and IBS (at IBS it's already submitted)
> Add the version to the last changelog

- kitchensink-formula/LICENSE
- kitchensink-formula/kitchensink-formula.changes
- kitchensink-formula/kitchensink-formula.spec
- kitchensink-formula/metadata/form.yml
- kitchensink-formula/metadata/metadata.yml
Example showing all formula forms features.
> WIP: Kitchen sink example

- cpu-mitigations-formula/states/init.sls
- cpu-mitigations-formula/states/map.jinja
* Avoid changing the grub config
* Add CPU mitigations options for Xen hypervisor
> Xen mitigations

- README.md
Applicable bug-fixes should be cherry-picked to stable branches. Currently one stable branch is maintained: `Manager-4.0`.
> Add note about stable branches

- grafana-formula/grafana-formula.changes
- grafana-formula/grafana/init.sls
Fixes [bsc#1182001](https://bugzilla.suse.com/show_bug.cgi?id=1182001).
> [grafana] Set `supported` to false for unsupported systems

- prometheus-exporters-formula/prometheus-exporters-formula.changes
Update changelog entries to be in sync with the released package.
> [Manager-4.1] Sync prometheus-exporters-formula changelog with the released package

- prometheus-exporters-formula/prometheus-exporters-formula.changes
- prometheus-exporters-formula/scripts/migrate_formula_data.py
> [Manager-4.1] Fix missing exporter in formula data migration

- virtualization-formulas/virtualization-formulas.spec
> virtualization: update copyright

- prometheus-formula/prometheus-formula.changes
- prometheus-formula/prometheus/files/prometheus_old.yml
- prometheus-formula/prometheus/init.sls
- prometheus-formula/prometheus/map.jinja
* Add support for new upstream Uyuni SD
(cherry picked from commit c4e2c1674656bc3e2be2f58a368a84df9714823a)
* Remove not supported TLS configuration
> [Manager-4.1] Add support for Prometheus>=2.31

- cpu-mitigations-formula/states/init.sls
- grafana-formula/grafana-formula.changes
- grafana-formula/grafana/init.sls
Add SLES 15 SP4 and openSUSE Leap 15.4 to supported versions
> Add support for SLES 15 SP4 and openSUSE Leap 15.4

- bind-formula/bind-formula.changes
- bind-formula/bind/files/suse/default
- bind-formula/bind/map.jinja
- remove chroot default usage as it was replaced by systemd
protections
Fixes https://github.com/SUSE/spacewalk/issues/16696
> Update defaults based on SLE15SP4 package

- Makefile
Signed-off-by: Ricardo Mateus <rmateus@suse.com>
update release version for uyuni configuration formula
> update version numbre for uyuni-config-formula

- prometheus-formula/README.md
- prometheus-formula/prometheus-formula.changes
- prometheus-formula/prometheus-formula.spec
Addresses https://github.com/SUSE/salt-formulas/pull/174#pullrequestreview-963172810
> Add README for Prometheus formula

- grafana-formula/grafana-formula.changes
- grafana-formula/grafana/files/mgr-client-systems.json.jinja
- grafana-formula/grafana/files/mgr-server.json.jinja
- grafana-formula/grafana/init.sls
Implements SUSE/spacewalk#19584
> [grafana] Set dashboard names depending on project name

- pxe-formula/pxe-formula.changes
- pxe-formula/pxe/terminal_entry.sls
Store  pxe configuration in grains. Needed for https://github.com/SUSE/spacewalk/issues/19489
> Store pxe configuration in grains

- grafana-formula/grafana-formula.changes
- grafana-formula/grafana/init.sls
Add SLE 15SP5 to supported versions in grafana formulas
> Add SLE 15SP5 to supported versions

- Makefile
- liberate-formula/LICENSE
- liberate-formula/README.md
- liberate-formula/liberate-formula.changes
- liberate-formula/liberate-formula.spec
- liberate-formula/liberate/init.sls
- liberate-formula/metadata/form.yml
- liberate-formula/metadata/metadata.yml
Add liberate formula from https://github.com/mmmmmmpc/liberate-formula
FIXES https://github.com/SUSE/spacewalk/issues/23012
> [liberate] Added liberate formula to migrate RedHat clones

- Makefile
- liberate-formula/liberate-formula.changes
This PR fixes the wrong year in the changelog and the version leftover :facepalm: :facepalm:
> [liberate] Fix changelog date and version

- liberate-formula/liberate-formula.spec
This PR fixes the licence and the copyright in the spec file.
> [liberate] Fix spec file

- grafana-formula/grafana-formula.changes
- grafana-formula/grafana-formula.spec
- grafana-formula/grafana/files/mgr-server.json.jinja
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1224786
Fix typo in mgr-server.json.jinja
> Fix mgr-server.json.jinja

- prometheus-formula/prometheus-formula.changes
- prometheus-formula/prometheus/init.sls
First check the installed package version then fall back to the newest available version.
> Fix checking Prometheus package version

- liberate-formula/liberate-formula.changes.kwalter.bsc1246981
- liberate-formula/liberate/init.sls
issue:  https://github.com/SUSE/spacewalk/issues/27932
> workaround for liberty 7 install (bsc#1246981)
